--Datenbank: Buchladen
--Tabellen: customers, orders

--1. ERMITTLE DIE ANZAHL DER KUNDEN NACH STÄDTEN. Sortierung nach Anzahl absteigend, dann nach Stadt aufsteigend.



--2. ERMITTLE, AUS WIEVIELE UNTERSCHIEDLICHEN STÄDTEN DIE KUNDEN KOMMEN.



--3. WIEVIEL UMSATZ HAT UNSER SHOP INSGESAMT GEMACHT?



--4. WIE HOCH WAR DER KLEINSTE EINKAUFSWERT?



--5. WIE HOCH IST DER DURCHSCHNITTLICHE EINKAUFSWERT?



--6. ALLE NACHNAMEN SOLLEN IN GROßBUCHSTABEN AUSGEGEBEN WERDEN UND NUR EINMAL ANGEZEIGT WERDEN 
--   UND AUFSTEIGEND SORTIERT WERDEN.



--7. NACHNAMEN UND VORNAMEN SOLLEN ZUSAMMEN IN EINER SPALTE AUSGEGEBEN WERDEN – AUFSTEIGEND SORTIERT; 
--   VORNAMEN SOLLEN VOLLSTÄNDIG KLEIN GESCHRIEBEN WERDEN; NACHNAME GROSS GESCHRIEBEN.
--   SPALTENÜBERSCHRIFT: KUNDE



--8. ES SOLLEN MAXIMAL DIE ERSTEN 5 ZEICHEN DES NACHNAMES AUSGEGEBEN WERDEN; aufsteigend sortiert.


--9. ES SOLLEN DIE VORNAMEN MIT DER ANZAHL AN BUCHSTABEN ABSTEIGEND SORTIERT AUSGEGEBEN WERDEN.
--   SPALTENÜBERSCHRIFT: LÄNGE VORNAME



--10. ERMITTELN SIE DEN KÜRZESTEN NACHNAMEN; SORTIERT NACH LÄNGE & NACHNAMEN.
--   SPALTENÜBERSCHRIFT: LÄNGE VORNAME



--11. WIEVIELE KUNDEN GEHÖREN ZU DER JÜNGSTEN ALTERSGRUPPE ALLER KUNDEN? SPALTE MIT ALTER SOLL 
--    MIT "ALTERSGRUPPE" ÜBERCHRIEBEN SEIN, SPALTE MIT ANZAHL DER KUNDEN MIT "ANZAHL". 



--12. LASSEN SIE SICH EINEN BENUTZERNAME AUSGEBEN, DER SICH ZUSAMMENSETZT AUS "Vorname.Nachname" 
--    aufsteigend sortiert.


--13. DIE KONVENTION FÜR IHRE EMAIL-ADRESSEN LAUTET: v.nachname@firma.de
--ERSTELLEN SIE EINE EMAILLISTE AUS NACHNAME UND VORNAMEN DER KUNDEN

