-- Datenbank: buchladen
-- Tabellen: customers, books, orders

--1. ZEIGE ALLE TITEL UND NACHNAMEN DER KUNDEN AN UND SORTIERE NACH NACHNAMEN.

--2. ZEIGE DOPPELTE NACHNAMEN DER KUNDEN NICHT AN UND SORTIERE NACH NACHNAMEN.

--3. ZEIGE NACHNAMEN, VORNAMEN, STADT DER KUNDEN UND SORTIERE NACH STADT, NACHNAME UND VORNAMEN AUFSTEIGEND.

--4. ZEIGE TITEL DER BÜCHER ABSTEIGEND AN.

--5. ZEIGE BESTELLUNGEN NACH DATUM ABSTEIGEND AN.

--6. ZEIGE KUNDEN-ID & BESTELLWERT DER BESTELLUNGEN AN UND SORTIERE NACH BESTELLWERT AUFSTEIGEND & KUNDEN-ID 
--   ABSTEIGEND.

--7. ZEIGE BESTELLWERTE & KUNDEN-ID DER BESTELLUNGEN AN UND SORTIERE NACH KUNDEN-ID ABSTEIGEND UND BESTELLWERT 
--   AUFSTEIGEND.

