--Datenbank: buchladen
--Tabellen: customers, books, books_subjects

--1. ZEIGE ALLE KUNDEN, DIE IN „Duisburg“ wohnen.



--2. ZEIGE KUNDEN, DIE EINEN GMX-EMAIL-ACCOUNT HABEN. Sortierung nach Nachnamen.



--3. ZEIGE ALLE KUNDEN, DEREN VORNAME MIT „D“ BEGINNT. Sortierung nach Vornamen.



--4. ZEIGE ALLE KUNDEN, DIE EINEN PROFESSORENTITEL HABEN.



--5. ZEIGE ALLE KUNDEN, DIE KEINEN AKADEMISCHEN GRAD HABEN. Sortierung nach Anrede, 
--   dann nach Nachnamen absteigend.



--6. ZEIGE ALLE GESCHÄFTSFÄHIGEN KUNDEN AN. Sortierung nach Alter und Stadt.




--7. ZEIGE ALLE KUNDEN AN, DIE ZWISCHEN 20 UND 30 JAHREN ALT SIND. SORTIERUNG NACH ALTER.




--8. ZEIGE ALLE KUNDEN AN, DIE IN RENTE SIND (>65 Jahre). Sortierung nach Alter absteigend.



--9. ERMITTLE DIE ANZAHL DER RENTNER.



--10. ZEIGE ALLE BÜCHER AN, BEI DENEN KEIN CREATOR ANGEGEBEN IST.



--11. ZEIGE ALLE BÜCHER AN, DIE ESSAYS ENTHALTEN.
-- Hinweis: Sie benötigen zunächst die subject_id für Essays




--12. ZEIGE DAS BUCH AN, DAS BEI GUTENBERG.ORG DIE ZAHL 15970 TRÄGT.



--13. WIE VIELE BÜCHER FÜHRT UNSER BUCHLADEN INSGESAMT?



--14. WIE HOCH IST DER GESAMTUMSATZ UNSERES BUCHLADENS? WÄHLEN SIE ALS SPALTENÜBERSCHRIFT "GESAMTUMSATZ":



--15. WIE HOCH IST DER GRÖßTE UMSATZ EINES KUNDEN? SPALTENÜBERSCHRIFT: GRÖßTER UMSATZ

